server:
  port: 8888
spring:
  application:
    name: my-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
      label: master